"""init tables

Revision ID: 9f9fb2d8d935
Revises: 
Create Date: 2026-04-24 22:53:59.201477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9fb2d8d935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing_item',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('gender_tags', sa.JSON(), nullable=True),
    sa.Column('color_tags', sa.JSON(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('try_on_asset', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('vision_labels', sa.JSON(), nullable=True),
    sa.Column('trending_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clothing_item_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_item_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_item_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_item_source'), ['source'], unique=False)

    op.create_table('outfit',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_owner_id'), ['owner_id'], unique=False)

    op.create_table('outfit_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.String(length=64), nullable=False),
    sa.Column('clothing_item_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_item_clothing_item_id'), ['clothing_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfit_item_outfit_id'), ['outfit_id'], unique=False)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth0_id', sa.String(length=255), nullable=False),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('brand_prefs', sa.JSON(), nullable=True),
    sa.Column('color_prefs', sa.JSON(), nullable=True),
    sa.Column('gender_pref', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_auth0_id'), ['auth0_id'], unique=True)

    op.create_table('user_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth0_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('onboarding_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_record_auth0_id'), ['auth0_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_record_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_record_email'))
        batch_op.drop_index(batch_op.f('ix_user_record_auth0_id'))

    op.drop_table('user_record')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_auth0_id'))

    op.drop_table('user_profile')
    with op.batch_alter_table('outfit_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_item_outfit_id'))
        batch_op.drop_index(batch_op.f('ix_outfit_item_clothing_item_id'))

    op.drop_table('outfit_item')
    with op.batch_alter_table('outfit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_owner_id'))

    op.drop_table('outfit')
    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clothing_item_source'))
        batch_op.drop_index(batch_op.f('ix_clothing_item_owner_id'))
        batch_op.drop_index(batch_op.f('ix_clothing_item_category'))
        batch_op.drop_index(batch_op.f('ix_clothing_item_brand'))

    op.drop_table('clothing_item')
    # ### end Alembic commands ###
